version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: amazon_dispute_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s  # Check every 5 seconds
      timeout: 10s  # Wait up to 10 seconds for database to be ready
      retries: 20   # Retry up to 20 times before considering unhealthy


  web:
    build: .
    command: /wait-for-postgres.sh db python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/amazon_dispute_db
      - DATABASE_DB=amazon_dispute_db
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=admin

